### ISSUE TITLE
ajuda a correr o bot

### ISSUE THREAD

**Issue by ceif** [souocare/bot-infodiaria-pt#1]
boas, 
ando a dar os primeiros passos com telegram+bot
1 - criei o bot no telegram e anotei o token do bot
2- criei um file .env na raiz do projeto e inseri a variável Telegram_Token='123456789:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' (o token é exemplificativo).
Weatherapi_key='aaaaa'

3- depois corro o comando python3 main.py
4- quando vou ao bot no telegram e escrevo /start não acontece nada.

necessito de configurar mais alguma coisa?

**Comment by ceif** [comment]
Já está resolvido.
Faltava correr o comando python3 db.py antes de correr o main.py

**Comment by souocare** [comment]
Ainda bem que conseguiu correr! Se precisar de ajuda, diga. Que tudo o que conseguir ajudar, o farei!
